# test
name: Deploy
on:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    if: github.event.issue.pull_request != null
    steps:
      - uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
      - name: Deploy UIReview
        if: github.event.comment.body == '!github deploy-uireview'
        run: |
          echo deploy uireview
          echo ${{ steps.set-target-branch.outputs.result/ }}
      - name: Deploy Staging
        if: github.event.comment.body == '!github deploy-staging'
        run: |
          echo deploy staging
          echo ${{ steps.set-target-branch.outputs.result/ }}
